name: CD

on:
  pull_request:
    types: [closed]
    branches: [dev]

jobs:
  cd-dev:
    name: Deploy
    environment:
      name: development
      url: http://wealth-marble-dev.kro.kr/
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          timeout: 30s
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd wealth-marble-frontend-dev
            git pull
            npm i -f
            npm run build
            pm2 delete wealth-marble-dev
            pm2 start npm --name "wealth-marble-dev" -- run start:dev
